/**
 * generated by Xtext 2.13.0
 */
package org.xtext.go;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>array Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.go.arrayType#getArrayLength <em>Array Length</em>}</li>
 *   <li>{@link org.xtext.go.arrayType#getElementType <em>Element Type</em>}</li>
 * </ul>
 *
 * @see org.xtext.go.GoPackage#getarrayType()
 * @model
 * @generated
 */
public interface arrayType extends EObject
{
  /**
   * Returns the value of the '<em><b>Array Length</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Array Length</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Array Length</em>' containment reference.
   * @see #setArrayLength(arrayLength)
   * @see org.xtext.go.GoPackage#getarrayType_ArrayLength()
   * @model containment="true"
   * @generated
   */
  arrayLength getArrayLength();

  /**
   * Sets the value of the '{@link org.xtext.go.arrayType#getArrayLength <em>Array Length</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Array Length</em>' containment reference.
   * @see #getArrayLength()
   * @generated
   */
  void setArrayLength(arrayLength value);

  /**
   * Returns the value of the '<em><b>Element Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Element Type</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Element Type</em>' containment reference.
   * @see #setElementType(elementType)
   * @see org.xtext.go.GoPackage#getarrayType_ElementType()
   * @model containment="true"
   * @generated
   */
  elementType getElementType();

  /**
   * Sets the value of the '{@link org.xtext.go.arrayType#getElementType <em>Element Type</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Element Type</em>' containment reference.
   * @see #getElementType()
   * @generated
   */
  void setElementType(elementType value);

} // arrayType
