/**
 * generated by Xtext 2.13.0
 */
package org.xtext.go;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.go.GoPackage#getDeclaration()
 * @model
 * @generated
 */
public interface Declaration extends Statement
{
} // Declaration
