/**
 * generated by Xtext 2.14.0
 */
package org.xtext.go;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>declaration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link org.xtext.go.declaration#getDecl <em>Decl</em>}</li>
 * </ul>
 * </p>
 *
 * @see org.xtext.go.GoPackage#getdeclaration()
 * @model
 * @generated
 */
public interface declaration extends EObject
{
  /**
   * Returns the value of the '<em><b>Decl</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Decl</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Decl</em>' containment reference.
   * @see #setDecl(EObject)
   * @see org.xtext.go.GoPackage#getdeclaration_Decl()
   * @model containment="true"
   * @generated
   */
  EObject getDecl();

  /**
   * Sets the value of the '{@link org.xtext.go.declaration#getDecl <em>Decl</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Decl</em>' containment reference.
   * @see #getDecl()
   * @generated
   */
  void setDecl(EObject value);

} // declaration
