/**
 * generated by Xtext 2.13.0
 */
package org.xtext.go;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>expression List</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.go.expressionList#getExpression <em>Expression</em>}</li>
 * </ul>
 *
 * @see org.xtext.go.GoPackage#getexpressionList()
 * @model
 * @generated
 */
public interface expressionList extends EObject
{
  /**
   * Returns the value of the '<em><b>Expression</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.go.expression}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expression</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expression</em>' containment reference list.
   * @see org.xtext.go.GoPackage#getexpressionList_Expression()
   * @model containment="true"
   * @generated
   */
  EList<expression> getExpression();

} // expressionList
