/**
 * generated by Xtext 2.13.0
 */
package org.xtext.go;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.go.Expression#getUnary_expr <em>Unary expr</em>}</li>
 *   <li>{@link org.xtext.go.Expression#getExpression_line <em>Expression line</em>}</li>
 * </ul>
 *
 * @see org.xtext.go.GoPackage#getExpression()
 * @model
 * @generated
 */
public interface Expression extends Operand, Expression_stmt, Go_stmt, Defer_stmt
{
  /**
   * Returns the value of the '<em><b>Unary expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Unary expr</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Unary expr</em>' containment reference.
   * @see #setUnary_expr(Unary_expr)
   * @see org.xtext.go.GoPackage#getExpression_Unary_expr()
   * @model containment="true"
   * @generated
   */
  Unary_expr getUnary_expr();

  /**
   * Sets the value of the '{@link org.xtext.go.Expression#getUnary_expr <em>Unary expr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Unary expr</em>' containment reference.
   * @see #getUnary_expr()
   * @generated
   */
  void setUnary_expr(Unary_expr value);

  /**
   * Returns the value of the '<em><b>Expression line</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expression line</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expression line</em>' containment reference.
   * @see #setExpression_line(Expression_line)
   * @see org.xtext.go.GoPackage#getExpression_Expression_line()
   * @model containment="true"
   * @generated
   */
  Expression_line getExpression_line();

  /**
   * Sets the value of the '{@link org.xtext.go.Expression#getExpression_line <em>Expression line</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expression line</em>' containment reference.
   * @see #getExpression_line()
   * @generated
   */
  void setExpression_line(Expression_line value);

} // Expression
