/**
 * generated by Xtext 2.13.0
 */
package org.xtext.go;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Function body</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.go.GoPackage#getFunction_body()
 * @model
 * @generated
 */
public interface Function_body extends Function_decl
{
} // Function_body
