/**
 * generated by Xtext 2.14.0
 */
package org.xtext.go;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>if Stmt</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link org.xtext.go.ifStmt#getSimplStatement <em>Simpl Statement</em>}</li>
 *   <li>{@link org.xtext.go.ifStmt#getExpr <em>Expr</em>}</li>
 *   <li>{@link org.xtext.go.ifStmt#getCodeBlock <em>Code Block</em>}</li>
 *   <li>{@link org.xtext.go.ifStmt#getIfStatement <em>If Statement</em>}</li>
 *   <li>{@link org.xtext.go.ifStmt#getCodeBlockIf <em>Code Block If</em>}</li>
 * </ul>
 * </p>
 *
 * @see org.xtext.go.GoPackage#getifStmt()
 * @model
 * @generated
 */
public interface ifStmt extends EObject
{
  /**
   * Returns the value of the '<em><b>Simpl Statement</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Simpl Statement</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Simpl Statement</em>' containment reference.
   * @see #setSimplStatement(simpleStmt)
   * @see org.xtext.go.GoPackage#getifStmt_SimplStatement()
   * @model containment="true"
   * @generated
   */
  simpleStmt getSimplStatement();

  /**
   * Sets the value of the '{@link org.xtext.go.ifStmt#getSimplStatement <em>Simpl Statement</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Simpl Statement</em>' containment reference.
   * @see #getSimplStatement()
   * @generated
   */
  void setSimplStatement(simpleStmt value);

  /**
   * Returns the value of the '<em><b>Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expr</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expr</em>' containment reference.
   * @see #setExpr(expression)
   * @see org.xtext.go.GoPackage#getifStmt_Expr()
   * @model containment="true"
   * @generated
   */
  expression getExpr();

  /**
   * Sets the value of the '{@link org.xtext.go.ifStmt#getExpr <em>Expr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expr</em>' containment reference.
   * @see #getExpr()
   * @generated
   */
  void setExpr(expression value);

  /**
   * Returns the value of the '<em><b>Code Block</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Code Block</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Code Block</em>' containment reference.
   * @see #setCodeBlock(block)
   * @see org.xtext.go.GoPackage#getifStmt_CodeBlock()
   * @model containment="true"
   * @generated
   */
  block getCodeBlock();

  /**
   * Sets the value of the '{@link org.xtext.go.ifStmt#getCodeBlock <em>Code Block</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Code Block</em>' containment reference.
   * @see #getCodeBlock()
   * @generated
   */
  void setCodeBlock(block value);

  /**
   * Returns the value of the '<em><b>If Statement</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>If Statement</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>If Statement</em>' containment reference.
   * @see #setIfStatement(ifStmt)
   * @see org.xtext.go.GoPackage#getifStmt_IfStatement()
   * @model containment="true"
   * @generated
   */
  ifStmt getIfStatement();

  /**
   * Sets the value of the '{@link org.xtext.go.ifStmt#getIfStatement <em>If Statement</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>If Statement</em>' containment reference.
   * @see #getIfStatement()
   * @generated
   */
  void setIfStatement(ifStmt value);

  /**
   * Returns the value of the '<em><b>Code Block If</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Code Block If</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Code Block If</em>' containment reference.
   * @see #setCodeBlockIf(block)
   * @see org.xtext.go.GoPackage#getifStmt_CodeBlockIf()
   * @model containment="true"
   * @generated
   */
  block getCodeBlockIf();

  /**
   * Sets the value of the '{@link org.xtext.go.ifStmt#getCodeBlockIf <em>Code Block If</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Code Block If</em>' containment reference.
   * @see #getCodeBlockIf()
   * @generated
   */
  void setCodeBlockIf(block value);

} // ifStmt
