/**
 * generated by Xtext 2.13.0
 */
package org.xtext.go;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Operand</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.go.GoPackage#getOperand()
 * @model
 * @generated
 */
public interface Operand extends Primary_expr
{
} // Operand
