/**
 * generated by Xtext 2.13.0
 */
package org.xtext.go;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>operand Name</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.go.operandName#getQualifiedIdent <em>Qualified Ident</em>}</li>
 * </ul>
 *
 * @see org.xtext.go.GoPackage#getoperandName()
 * @model
 * @generated
 */
public interface operandName extends EObject
{
  /**
   * Returns the value of the '<em><b>Qualified Ident</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Qualified Ident</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Qualified Ident</em>' attribute.
   * @see #setQualifiedIdent(String)
   * @see org.xtext.go.GoPackage#getoperandName_QualifiedIdent()
   * @model
   * @generated
   */
  String getQualifiedIdent();

  /**
   * Sets the value of the '{@link org.xtext.go.operandName#getQualifiedIdent <em>Qualified Ident</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Qualified Ident</em>' attribute.
   * @see #getQualifiedIdent()
   * @generated
   */
  void setQualifiedIdent(String value);

} // operandName
