/**
 * generated by Xtext 2.13.0
 */
package org.xtext.go;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>primary Expr Slice</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.go.primaryExprSlice#getPrimaryExprStuff <em>Primary Expr Stuff</em>}</li>
 *   <li>{@link org.xtext.go.primaryExprSlice#getPrimaryExprSlice <em>Primary Expr Slice</em>}</li>
 * </ul>
 *
 * @see org.xtext.go.GoPackage#getprimaryExprSlice()
 * @model
 * @generated
 */
public interface primaryExprSlice extends EObject
{
  /**
   * Returns the value of the '<em><b>Primary Expr Stuff</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Primary Expr Stuff</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Primary Expr Stuff</em>' containment reference.
   * @see #setPrimaryExprStuff(primaryExprStuff)
   * @see org.xtext.go.GoPackage#getprimaryExprSlice_PrimaryExprStuff()
   * @model containment="true"
   * @generated
   */
  primaryExprStuff getPrimaryExprStuff();

  /**
   * Sets the value of the '{@link org.xtext.go.primaryExprSlice#getPrimaryExprStuff <em>Primary Expr Stuff</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Primary Expr Stuff</em>' containment reference.
   * @see #getPrimaryExprStuff()
   * @generated
   */
  void setPrimaryExprStuff(primaryExprStuff value);

  /**
   * Returns the value of the '<em><b>Primary Expr Slice</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Primary Expr Slice</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Primary Expr Slice</em>' containment reference.
   * @see #setPrimaryExprSlice(primaryExprSlice)
   * @see org.xtext.go.GoPackage#getprimaryExprSlice_PrimaryExprSlice()
   * @model containment="true"
   * @generated
   */
  primaryExprSlice getPrimaryExprSlice();

  /**
   * Sets the value of the '{@link org.xtext.go.primaryExprSlice#getPrimaryExprSlice <em>Primary Expr Slice</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Primary Expr Slice</em>' containment reference.
   * @see #getPrimaryExprSlice()
   * @generated
   */
  void setPrimaryExprSlice(primaryExprSlice value);

} // primaryExprSlice
