/**
 * generated by Xtext 2.14.0
 */
package org.xtext.go;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>send Stmt</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * <ul>
 *   <li>{@link org.xtext.go.sendStmt#getExpr1 <em>Expr1</em>}</li>
 *   <li>{@link org.xtext.go.sendStmt#getExpr2 <em>Expr2</em>}</li>
 * </ul>
 * </p>
 *
 * @see org.xtext.go.GoPackage#getsendStmt()
 * @model
 * @generated
 */
public interface sendStmt extends EObject
{
  /**
   * Returns the value of the '<em><b>Expr1</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expr1</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expr1</em>' containment reference.
   * @see #setExpr1(expression)
   * @see org.xtext.go.GoPackage#getsendStmt_Expr1()
   * @model containment="true"
   * @generated
   */
  expression getExpr1();

  /**
   * Sets the value of the '{@link org.xtext.go.sendStmt#getExpr1 <em>Expr1</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expr1</em>' containment reference.
   * @see #getExpr1()
   * @generated
   */
  void setExpr1(expression value);

  /**
   * Returns the value of the '<em><b>Expr2</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Expr2</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expr2</em>' containment reference.
   * @see #setExpr2(expression)
   * @see org.xtext.go.GoPackage#getsendStmt_Expr2()
   * @model containment="true"
   * @generated
   */
  expression getExpr2();

  /**
   * Sets the value of the '{@link org.xtext.go.sendStmt#getExpr2 <em>Expr2</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expr2</em>' containment reference.
   * @see #getExpr2()
   * @generated
   */
  void setExpr2(expression value);

} // sendStmt
