/**
 * generated by Xtext 2.14.0
 */
package org.xtext.go;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>type Case Clause</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.go.typeCaseClause#getTypeSwitchCase <em>Type Switch Case</em>}</li>
 *   <li>{@link org.xtext.go.typeCaseClause#getStatementList <em>Statement List</em>}</li>
 * </ul>
 *
 * @see org.xtext.go.GoPackage#gettypeCaseClause()
 * @model
 * @generated
 */
public interface typeCaseClause extends EObject
{
  /**
   * Returns the value of the '<em><b>Type Switch Case</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Type Switch Case</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type Switch Case</em>' containment reference.
   * @see #setTypeSwitchCase(typeSwitchCase)
   * @see org.xtext.go.GoPackage#gettypeCaseClause_TypeSwitchCase()
   * @model containment="true"
   * @generated
   */
  typeSwitchCase getTypeSwitchCase();

  /**
   * Sets the value of the '{@link org.xtext.go.typeCaseClause#getTypeSwitchCase <em>Type Switch Case</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type Switch Case</em>' containment reference.
   * @see #getTypeSwitchCase()
   * @generated
   */
  void setTypeSwitchCase(typeSwitchCase value);

  /**
   * Returns the value of the '<em><b>Statement List</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Statement List</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Statement List</em>' containment reference.
   * @see #setStatementList(statementList)
   * @see org.xtext.go.GoPackage#gettypeCaseClause_StatementList()
   * @model containment="true"
   * @generated
   */
  statementList getStatementList();

  /**
   * Sets the value of the '{@link org.xtext.go.typeCaseClause#getStatementList <em>Statement List</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Statement List</em>' containment reference.
   * @see #getStatementList()
   * @generated
   */
  void setStatementList(statementList value);

} // typeCaseClause
