/**
 * generated by Xtext 2.14.0
 */
package org.xtext.go;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>unary Expr</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.go.unaryExpr#getPrimaryExpr <em>Primary Expr</em>}</li>
 *   <li>{@link org.xtext.go.unaryExpr#getUnaryExpr <em>Unary Expr</em>}</li>
 * </ul>
 *
 * @see org.xtext.go.GoPackage#getunaryExpr()
 * @model
 * @generated
 */
public interface unaryExpr extends EObject
{
  /**
   * Returns the value of the '<em><b>Primary Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Primary Expr</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Primary Expr</em>' containment reference.
   * @see #setPrimaryExpr(primaryExpr)
   * @see org.xtext.go.GoPackage#getunaryExpr_PrimaryExpr()
   * @model containment="true"
   * @generated
   */
  primaryExpr getPrimaryExpr();

  /**
   * Sets the value of the '{@link org.xtext.go.unaryExpr#getPrimaryExpr <em>Primary Expr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Primary Expr</em>' containment reference.
   * @see #getPrimaryExpr()
   * @generated
   */
  void setPrimaryExpr(primaryExpr value);

  /**
   * Returns the value of the '<em><b>Unary Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Unary Expr</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Unary Expr</em>' containment reference.
   * @see #setUnaryExpr(unaryExpr)
   * @see org.xtext.go.GoPackage#getunaryExpr_UnaryExpr()
   * @model containment="true"
   * @generated
   */
  unaryExpr getUnaryExpr();

  /**
   * Sets the value of the '{@link org.xtext.go.unaryExpr#getUnaryExpr <em>Unary Expr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Unary Expr</em>' containment reference.
   * @see #getUnaryExpr()
   * @generated
   */
  void setUnaryExpr(unaryExpr value);

} // unaryExpr
