/**
 * generated by Xtext 2.13.0
 */
package org.xtext.validation;

import org.xtext.go.expression;
import org.xtext.go.expressionMatched;
import org.xtext.go.primaryExpr;
import org.xtext.go.unaryExpr;
import org.xtext.validation.AbstractGoValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class GoValidator extends AbstractGoValidator {
  /* @Check
   */public Object checkExpression(final expression expression) {
    throw new Error("Unresolved compilation problems:"
      + "\n!== cannot be resolved."
      + "\n!== cannot be resolved.");
  }
  
  public Object checkMatched(final expressionMatched matched) {
    throw new Error("Unresolved compilation problems:"
      + "\n!== cannot be resolved.");
  }
  
  public Object checkUnary(final unaryExpr expr) {
    throw new Error("Unresolved compilation problems:"
      + "\n!== cannot be resolved.");
  }
  
  public Object checkPrimary(final primaryExpr expr) {
    return null;
  }
}
