/**
 * generated by Xtext 2.13.0
 */
package org.xtext.validation;

import org.eclipse.xtext.validation.Check;
import org.xtext.go.ifStmt;
import org.xtext.go.simpleStmt;
import org.xtext.validation.AbstractGoValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class GoValidator extends AbstractGoValidator {
  @Check
  public Object checkUniqueId(final ifStmt stmt) {
    Object _xifexpression = null;
    simpleStmt _simpleStmt = stmt.getSimpleStmt();
    boolean _tripleNotEquals = (_simpleStmt != null);
    if (_tripleNotEquals) {
      _xifexpression = null;
    }
    return _xifexpression;
  }
}
