/**
 * generated by Xtext 2.14.0
 */
package org.xtext.go.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.go.GoPackage;
import org.xtext.go.elementList;
import org.xtext.go.keyedElement;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>element List</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * <ul>
 *   <li>{@link org.xtext.go.impl.elementListImpl#getKeyedElement <em>Keyed Element</em>}</li>
 * </ul>
 * </p>
 *
 * @generated
 */
public class elementListImpl extends MinimalEObjectImpl.Container implements elementList
{
  /**
   * The cached value of the '{@link #getKeyedElement() <em>Keyed Element</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getKeyedElement()
   * @generated
   * @ordered
   */
  protected keyedElement keyedElement;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected elementListImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GoPackage.Literals.ELEMENT_LIST;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public keyedElement getKeyedElement()
  {
    return keyedElement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetKeyedElement(keyedElement newKeyedElement, NotificationChain msgs)
  {
    keyedElement oldKeyedElement = keyedElement;
    keyedElement = newKeyedElement;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, GoPackage.ELEMENT_LIST__KEYED_ELEMENT, oldKeyedElement, newKeyedElement);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setKeyedElement(keyedElement newKeyedElement)
  {
    if (newKeyedElement != keyedElement)
    {
      NotificationChain msgs = null;
      if (keyedElement != null)
        msgs = ((InternalEObject)keyedElement).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - GoPackage.ELEMENT_LIST__KEYED_ELEMENT, null, msgs);
      if (newKeyedElement != null)
        msgs = ((InternalEObject)newKeyedElement).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - GoPackage.ELEMENT_LIST__KEYED_ELEMENT, null, msgs);
      msgs = basicSetKeyedElement(newKeyedElement, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GoPackage.ELEMENT_LIST__KEYED_ELEMENT, newKeyedElement, newKeyedElement));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case GoPackage.ELEMENT_LIST__KEYED_ELEMENT:
        return basicSetKeyedElement(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GoPackage.ELEMENT_LIST__KEYED_ELEMENT:
        return getKeyedElement();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GoPackage.ELEMENT_LIST__KEYED_ELEMENT:
        setKeyedElement((keyedElement)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GoPackage.ELEMENT_LIST__KEYED_ELEMENT:
        setKeyedElement((keyedElement)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GoPackage.ELEMENT_LIST__KEYED_ELEMENT:
        return keyedElement != null;
    }
    return super.eIsSet(featureID);
  }

} //elementListImpl
