/**
 * generated by Xtext 2.13.0
 */
package org.xtext.go.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.go.GoPackage;
import org.xtext.go.Go_stmt;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Go stmt</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class Go_stmtImpl extends StatementImpl implements Go_stmt
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected Go_stmtImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GoPackage.Literals.GO_STMT;
  }

} //Go_stmtImpl
