/**
 * generated by Xtext 2.13.0
 */
package org.xtext.go.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.go.GoPackage;
import org.xtext.go.index;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>index</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class indexImpl extends MinimalEObjectImpl.Container implements index
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected indexImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GoPackage.Literals.INDEX;
  }

} //indexImpl
