/**
 * generated by Xtext 2.14.0
 */
package org.xtext.go.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.go.GoPackage;
import org.xtext.go.primaryExprIndex;
import org.xtext.go.primaryExprStuff;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>primary Expr Index</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.go.impl.primaryExprIndexImpl#getContent <em>Content</em>}</li>
 *   <li>{@link org.xtext.go.impl.primaryExprIndexImpl#getPrimaryExprIndex <em>Primary Expr Index</em>}</li>
 * </ul>
 *
 * @generated
 */
public class primaryExprIndexImpl extends MinimalEObjectImpl.Container implements primaryExprIndex
{
  /**
   * The cached value of the '{@link #getContent() <em>Content</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getContent()
   * @generated
   * @ordered
   */
  protected primaryExprStuff content;

  /**
   * The cached value of the '{@link #getPrimaryExprIndex() <em>Primary Expr Index</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPrimaryExprIndex()
   * @generated
   * @ordered
   */
  protected primaryExprIndex primaryExprIndex;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected primaryExprIndexImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GoPackage.Literals.PRIMARY_EXPR_INDEX;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public primaryExprStuff getContent()
  {
    return content;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetContent(primaryExprStuff newContent, NotificationChain msgs)
  {
    primaryExprStuff oldContent = content;
    content = newContent;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, GoPackage.PRIMARY_EXPR_INDEX__CONTENT, oldContent, newContent);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setContent(primaryExprStuff newContent)
  {
    if (newContent != content)
    {
      NotificationChain msgs = null;
      if (content != null)
        msgs = ((InternalEObject)content).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - GoPackage.PRIMARY_EXPR_INDEX__CONTENT, null, msgs);
      if (newContent != null)
        msgs = ((InternalEObject)newContent).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - GoPackage.PRIMARY_EXPR_INDEX__CONTENT, null, msgs);
      msgs = basicSetContent(newContent, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GoPackage.PRIMARY_EXPR_INDEX__CONTENT, newContent, newContent));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public primaryExprIndex getPrimaryExprIndex()
  {
    return primaryExprIndex;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetPrimaryExprIndex(primaryExprIndex newPrimaryExprIndex, NotificationChain msgs)
  {
    primaryExprIndex oldPrimaryExprIndex = primaryExprIndex;
    primaryExprIndex = newPrimaryExprIndex;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, GoPackage.PRIMARY_EXPR_INDEX__PRIMARY_EXPR_INDEX, oldPrimaryExprIndex, newPrimaryExprIndex);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setPrimaryExprIndex(primaryExprIndex newPrimaryExprIndex)
  {
    if (newPrimaryExprIndex != primaryExprIndex)
    {
      NotificationChain msgs = null;
      if (primaryExprIndex != null)
        msgs = ((InternalEObject)primaryExprIndex).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - GoPackage.PRIMARY_EXPR_INDEX__PRIMARY_EXPR_INDEX, null, msgs);
      if (newPrimaryExprIndex != null)
        msgs = ((InternalEObject)newPrimaryExprIndex).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - GoPackage.PRIMARY_EXPR_INDEX__PRIMARY_EXPR_INDEX, null, msgs);
      msgs = basicSetPrimaryExprIndex(newPrimaryExprIndex, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GoPackage.PRIMARY_EXPR_INDEX__PRIMARY_EXPR_INDEX, newPrimaryExprIndex, newPrimaryExprIndex));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case GoPackage.PRIMARY_EXPR_INDEX__CONTENT:
        return basicSetContent(null, msgs);
      case GoPackage.PRIMARY_EXPR_INDEX__PRIMARY_EXPR_INDEX:
        return basicSetPrimaryExprIndex(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GoPackage.PRIMARY_EXPR_INDEX__CONTENT:
        return getContent();
      case GoPackage.PRIMARY_EXPR_INDEX__PRIMARY_EXPR_INDEX:
        return getPrimaryExprIndex();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GoPackage.PRIMARY_EXPR_INDEX__CONTENT:
        setContent((primaryExprStuff)newValue);
        return;
      case GoPackage.PRIMARY_EXPR_INDEX__PRIMARY_EXPR_INDEX:
        setPrimaryExprIndex((primaryExprIndex)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GoPackage.PRIMARY_EXPR_INDEX__CONTENT:
        setContent((primaryExprStuff)null);
        return;
      case GoPackage.PRIMARY_EXPR_INDEX__PRIMARY_EXPR_INDEX:
        setPrimaryExprIndex((primaryExprIndex)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GoPackage.PRIMARY_EXPR_INDEX__CONTENT:
        return content != null;
      case GoPackage.PRIMARY_EXPR_INDEX__PRIMARY_EXPR_INDEX:
        return primaryExprIndex != null;
    }
    return super.eIsSet(featureID);
  }

} //primaryExprIndexImpl
