/**
 * generated by Xtext 2.14.0
 */
package org.xtext.go.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.go.GoPackage;
import org.xtext.go.importDecl;
import org.xtext.go.packageClause;
import org.xtext.go.sourceFile;
import org.xtext.go.topLevelDecl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>source File</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * <ul>
 *   <li>{@link org.xtext.go.impl.sourceFileImpl#getPackage <em>Package</em>}</li>
 *   <li>{@link org.xtext.go.impl.sourceFileImpl#getImports <em>Imports</em>}</li>
 *   <li>{@link org.xtext.go.impl.sourceFileImpl#getTopLevelDecls <em>Top Level Decls</em>}</li>
 * </ul>
 * </p>
 *
 * @generated
 */
public class sourceFileImpl extends MinimalEObjectImpl.Container implements sourceFile
{
  /**
   * The cached value of the '{@link #getPackage() <em>Package</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPackage()
   * @generated
   * @ordered
   */
  protected packageClause package_;

  /**
   * The cached value of the '{@link #getImports() <em>Imports</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getImports()
   * @generated
   * @ordered
   */
  protected EList<importDecl> imports;

  /**
   * The cached value of the '{@link #getTopLevelDecls() <em>Top Level Decls</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTopLevelDecls()
   * @generated
   * @ordered
   */
  protected EList<topLevelDecl> topLevelDecls;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected sourceFileImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GoPackage.Literals.SOURCE_FILE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public packageClause getPackage()
  {
    return package_;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetPackage(packageClause newPackage, NotificationChain msgs)
  {
    packageClause oldPackage = package_;
    package_ = newPackage;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, GoPackage.SOURCE_FILE__PACKAGE, oldPackage, newPackage);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setPackage(packageClause newPackage)
  {
    if (newPackage != package_)
    {
      NotificationChain msgs = null;
      if (package_ != null)
        msgs = ((InternalEObject)package_).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - GoPackage.SOURCE_FILE__PACKAGE, null, msgs);
      if (newPackage != null)
        msgs = ((InternalEObject)newPackage).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - GoPackage.SOURCE_FILE__PACKAGE, null, msgs);
      msgs = basicSetPackage(newPackage, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GoPackage.SOURCE_FILE__PACKAGE, newPackage, newPackage));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<importDecl> getImports()
  {
    if (imports == null)
    {
      imports = new EObjectContainmentEList<importDecl>(importDecl.class, this, GoPackage.SOURCE_FILE__IMPORTS);
    }
    return imports;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<topLevelDecl> getTopLevelDecls()
  {
    if (topLevelDecls == null)
    {
      topLevelDecls = new EObjectContainmentEList<topLevelDecl>(topLevelDecl.class, this, GoPackage.SOURCE_FILE__TOP_LEVEL_DECLS);
    }
    return topLevelDecls;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case GoPackage.SOURCE_FILE__PACKAGE:
        return basicSetPackage(null, msgs);
      case GoPackage.SOURCE_FILE__IMPORTS:
        return ((InternalEList<?>)getImports()).basicRemove(otherEnd, msgs);
      case GoPackage.SOURCE_FILE__TOP_LEVEL_DECLS:
        return ((InternalEList<?>)getTopLevelDecls()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GoPackage.SOURCE_FILE__PACKAGE:
        return getPackage();
      case GoPackage.SOURCE_FILE__IMPORTS:
        return getImports();
      case GoPackage.SOURCE_FILE__TOP_LEVEL_DECLS:
        return getTopLevelDecls();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GoPackage.SOURCE_FILE__PACKAGE:
        setPackage((packageClause)newValue);
        return;
      case GoPackage.SOURCE_FILE__IMPORTS:
        getImports().clear();
        getImports().addAll((Collection<? extends importDecl>)newValue);
        return;
      case GoPackage.SOURCE_FILE__TOP_LEVEL_DECLS:
        getTopLevelDecls().clear();
        getTopLevelDecls().addAll((Collection<? extends topLevelDecl>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GoPackage.SOURCE_FILE__PACKAGE:
        setPackage((packageClause)null);
        return;
      case GoPackage.SOURCE_FILE__IMPORTS:
        getImports().clear();
        return;
      case GoPackage.SOURCE_FILE__TOP_LEVEL_DECLS:
        getTopLevelDecls().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GoPackage.SOURCE_FILE__PACKAGE:
        return package_ != null;
      case GoPackage.SOURCE_FILE__IMPORTS:
        return imports != null && !imports.isEmpty();
      case GoPackage.SOURCE_FILE__TOP_LEVEL_DECLS:
        return topLevelDecls != null && !topLevelDecls.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //sourceFileImpl
