/**
 * generated by Xtext 2.14.0
 */
package org.xtext.go.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.go.GoPackage;
import org.xtext.go.importDecl;
import org.xtext.go.sourceFile;
import org.xtext.go.topLevelDecl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>source File</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * <ul>
 *   <li>{@link org.xtext.go.impl.sourceFileImpl#getPackageClause <em>Package Clause</em>}</li>
 *   <li>{@link org.xtext.go.impl.sourceFileImpl#getImportDecl <em>Import Decl</em>}</li>
 *   <li>{@link org.xtext.go.impl.sourceFileImpl#getTopLevelDecl <em>Top Level Decl</em>}</li>
 * </ul>
 * </p>
 *
 * @generated
 */
public class sourceFileImpl extends MinimalEObjectImpl.Container implements sourceFile
{
  /**
   * The default value of the '{@link #getPackageClause() <em>Package Clause</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPackageClause()
   * @generated
   * @ordered
   */
  protected static final String PACKAGE_CLAUSE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getPackageClause() <em>Package Clause</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getPackageClause()
   * @generated
   * @ordered
   */
  protected String packageClause = PACKAGE_CLAUSE_EDEFAULT;

  /**
   * The cached value of the '{@link #getImportDecl() <em>Import Decl</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getImportDecl()
   * @generated
   * @ordered
   */
  protected EList<importDecl> importDecl;

  /**
   * The cached value of the '{@link #getTopLevelDecl() <em>Top Level Decl</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTopLevelDecl()
   * @generated
   * @ordered
   */
  protected EList<topLevelDecl> topLevelDecl;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected sourceFileImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GoPackage.Literals.SOURCE_FILE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getPackageClause()
  {
    return packageClause;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setPackageClause(String newPackageClause)
  {
    String oldPackageClause = packageClause;
    packageClause = newPackageClause;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GoPackage.SOURCE_FILE__PACKAGE_CLAUSE, oldPackageClause, packageClause));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<importDecl> getImportDecl()
  {
    if (importDecl == null)
    {
      importDecl = new EObjectContainmentEList<importDecl>(importDecl.class, this, GoPackage.SOURCE_FILE__IMPORT_DECL);
    }
    return importDecl;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<topLevelDecl> getTopLevelDecl()
  {
    if (topLevelDecl == null)
    {
      topLevelDecl = new EObjectContainmentEList<topLevelDecl>(topLevelDecl.class, this, GoPackage.SOURCE_FILE__TOP_LEVEL_DECL);
    }
    return topLevelDecl;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case GoPackage.SOURCE_FILE__IMPORT_DECL:
        return ((InternalEList<?>)getImportDecl()).basicRemove(otherEnd, msgs);
      case GoPackage.SOURCE_FILE__TOP_LEVEL_DECL:
        return ((InternalEList<?>)getTopLevelDecl()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GoPackage.SOURCE_FILE__PACKAGE_CLAUSE:
        return getPackageClause();
      case GoPackage.SOURCE_FILE__IMPORT_DECL:
        return getImportDecl();
      case GoPackage.SOURCE_FILE__TOP_LEVEL_DECL:
        return getTopLevelDecl();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GoPackage.SOURCE_FILE__PACKAGE_CLAUSE:
        setPackageClause((String)newValue);
        return;
      case GoPackage.SOURCE_FILE__IMPORT_DECL:
        getImportDecl().clear();
        getImportDecl().addAll((Collection<? extends importDecl>)newValue);
        return;
      case GoPackage.SOURCE_FILE__TOP_LEVEL_DECL:
        getTopLevelDecl().clear();
        getTopLevelDecl().addAll((Collection<? extends topLevelDecl>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GoPackage.SOURCE_FILE__PACKAGE_CLAUSE:
        setPackageClause(PACKAGE_CLAUSE_EDEFAULT);
        return;
      case GoPackage.SOURCE_FILE__IMPORT_DECL:
        getImportDecl().clear();
        return;
      case GoPackage.SOURCE_FILE__TOP_LEVEL_DECL:
        getTopLevelDecl().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GoPackage.SOURCE_FILE__PACKAGE_CLAUSE:
        return PACKAGE_CLAUSE_EDEFAULT == null ? packageClause != null : !PACKAGE_CLAUSE_EDEFAULT.equals(packageClause);
      case GoPackage.SOURCE_FILE__IMPORT_DECL:
        return importDecl != null && !importDecl.isEmpty();
      case GoPackage.SOURCE_FILE__TOP_LEVEL_DECL:
        return topLevelDecl != null && !topLevelDecl.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (packageClause: ");
    result.append(packageClause);
    result.append(')');
    return result.toString();
  }

} //sourceFileImpl
