/**
 * generated by Xtext 2.14.0
 */
package org.xtext.go.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.go.GoPackage;
import org.xtext.go.fieldDecl;
import org.xtext.go.structType;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>struct Type</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * <ul>
 *   <li>{@link org.xtext.go.impl.structTypeImpl#getFieldDecl <em>Field Decl</em>}</li>
 * </ul>
 * </p>
 *
 * @generated
 */
public class structTypeImpl extends MinimalEObjectImpl.Container implements structType
{
  /**
   * The cached value of the '{@link #getFieldDecl() <em>Field Decl</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFieldDecl()
   * @generated
   * @ordered
   */
  protected fieldDecl fieldDecl;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected structTypeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GoPackage.Literals.STRUCT_TYPE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public fieldDecl getFieldDecl()
  {
    return fieldDecl;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetFieldDecl(fieldDecl newFieldDecl, NotificationChain msgs)
  {
    fieldDecl oldFieldDecl = fieldDecl;
    fieldDecl = newFieldDecl;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, GoPackage.STRUCT_TYPE__FIELD_DECL, oldFieldDecl, newFieldDecl);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setFieldDecl(fieldDecl newFieldDecl)
  {
    if (newFieldDecl != fieldDecl)
    {
      NotificationChain msgs = null;
      if (fieldDecl != null)
        msgs = ((InternalEObject)fieldDecl).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - GoPackage.STRUCT_TYPE__FIELD_DECL, null, msgs);
      if (newFieldDecl != null)
        msgs = ((InternalEObject)newFieldDecl).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - GoPackage.STRUCT_TYPE__FIELD_DECL, null, msgs);
      msgs = basicSetFieldDecl(newFieldDecl, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, GoPackage.STRUCT_TYPE__FIELD_DECL, newFieldDecl, newFieldDecl));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case GoPackage.STRUCT_TYPE__FIELD_DECL:
        return basicSetFieldDecl(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GoPackage.STRUCT_TYPE__FIELD_DECL:
        return getFieldDecl();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GoPackage.STRUCT_TYPE__FIELD_DECL:
        setFieldDecl((fieldDecl)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GoPackage.STRUCT_TYPE__FIELD_DECL:
        setFieldDecl((fieldDecl)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GoPackage.STRUCT_TYPE__FIELD_DECL:
        return fieldDecl != null;
    }
    return super.eIsSet(featureID);
  }

} //structTypeImpl
