/**
 * generated by Xtext 2.14.0
 */
package org.xtext.go.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.go.GoPackage;
import org.xtext.go.fieldDecl;
import org.xtext.go.structType;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>struct Type</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.go.impl.structTypeImpl#getFieldsDecl <em>Fields Decl</em>}</li>
 * </ul>
 *
 * @generated
 */
public class structTypeImpl extends MinimalEObjectImpl.Container implements structType
{
  /**
   * The cached value of the '{@link #getFieldsDecl() <em>Fields Decl</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFieldsDecl()
   * @generated
   * @ordered
   */
  protected EList<fieldDecl> fieldsDecl;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected structTypeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return GoPackage.Literals.STRUCT_TYPE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<fieldDecl> getFieldsDecl()
  {
    if (fieldsDecl == null)
    {
      fieldsDecl = new EObjectContainmentEList<fieldDecl>(fieldDecl.class, this, GoPackage.STRUCT_TYPE__FIELDS_DECL);
    }
    return fieldsDecl;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case GoPackage.STRUCT_TYPE__FIELDS_DECL:
        return ((InternalEList<?>)getFieldsDecl()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case GoPackage.STRUCT_TYPE__FIELDS_DECL:
        return getFieldsDecl();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case GoPackage.STRUCT_TYPE__FIELDS_DECL:
        getFieldsDecl().clear();
        getFieldsDecl().addAll((Collection<? extends fieldDecl>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case GoPackage.STRUCT_TYPE__FIELDS_DECL:
        getFieldsDecl().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case GoPackage.STRUCT_TYPE__FIELDS_DECL:
        return fieldsDecl != null && !fieldsDecl.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //structTypeImpl
